apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp-nginx
    spec:
      containers:
      - name: webapp-nginx
        image: aqcitdevkubereg.azurecr.io/webapp-nginx:v1
        ports:
        - containerPort: 6379
          name: 
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-nginx
spec:
  ports:
  - port: 6379
  selector:
    app: webapp-nginx
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp-flask
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: webapp-flask
    spec:
      containers:
      - name: webapp-flask
        image: aqcitdevkubereg.azurecr.io/webapp-flask:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-flask
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: webapp-flask
